name: pana_client
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  data:
    path: ./data
  domain:
    path: ./domain
  navigation:
    path: ./navigation

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "core_ui/resources/images/logo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
