name: core
publish_to: none
description: Project core module

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.29.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  permission_handler: ^12.0.1
  injectable: ^2.5.1
  dev: ^1.0.0
  flutter_dotenv: ^6.0.0
  sentry_flutter: ^9.6.0
  fcuuid_kit: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.8.1
  build_runner: ^2.7.1

flutter:
  assets:
    - resources/lang/