name: domain
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.29.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

  json_annotation: ^4.9.0
  freezed: ^3.2.0
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.11.1
  build_runner: ^2.7.1
  injectable_generator: ^2.8.1
