name: user_profile
description: user profile feature
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core_ui:
    path: ../../core_ui
  flutter_bloc: ^9.1.1
  package_info_plus: ^9.0.0
  equatable: ^2.0.7
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
dev_dependencies:
  flutter_lints: ^6.0.0
