name: core_ui
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.29.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  flutter_svg: ^2.2.1
  flex_color_scheme: ^8.3.0
  cached_network_image: ^3.4.1
  intl_phone_field: ^3.2.0
  lucide_icons_flutter: ^3.1.0
  pinput: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - resources/icons/
    - resources/images/

  fonts:
    - family: Helvetica
      fonts:
        - asset: resources/fonts/Helvetica.ttf
          weight: 400