name: core_ui
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  flutter_svg: ^2.2.1
  flex_color_scheme: ^8.3.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - resources/icons/
    - resources/images/